apiVersion: v1
kind: Service
metadata:
  name: python-k8s
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: python-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-k8s
  template:
    metadata:
      labels:
        app: python-k8s
    spec:
      containers:
        - name: python-k8s
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 8080